# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-13 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 16, 53, 0, 694835, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
