# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190313_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
