# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-14 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190313_1924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useractivation',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 47, 48, 753502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='phone_num',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
