# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-14 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190313_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 11, 29, 41, 312860, tzinfo=utc)),
        ),
    ]
