# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-15 22:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_auto_20190314_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('date_activated', models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 15, 22, 0, 31, 935900, tzinfo=utc))),
                ('status', models.BooleanField(default=False)),
                ('t_and_c', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_activated',),
            },
        ),
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
