# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190315_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_activated',
            field=models.DateTimeField(null=True),
        ),
    ]
