# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190316_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
