# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190314_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 16, 0, 7, 50, 437503, tzinfo=utc)),
        ),
    ]
