# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190315_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 16, 9, 58, 3, 838132, tzinfo=utc)),
        ),
    ]
