# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190316_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 16, 13, 49, 24, 872492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(),
        ),
    ]
