# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 13:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190316_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 16, 13, 58, 36, 909845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
