# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190316_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
